config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  get '/' => 'welcome#index' , as: 'home'
  resources :desktops
  resources :laptops
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
      else
        can :read, :all
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/desktop.rb
class Desktop < ApplicationRecord
    validates :emp_id, :asset_num, :name, :MAC_address, presence: true
    mount_uploaders :images, DesktopUploader
end

app/models/laptop.rb
class Laptop < ApplicationRecord
    validates :emp_id, :asset_num, :name, :MAC_address, :charger_num, presence: true
    mount_uploaders :images, LaptopUploader
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
  validates :mobile, numericality: { only_integer: true }, length: { is: 10 }
  validates :username, presence: true, uniqueness: true

    after_create :signup_confirmation
    def signup_confirmation
      UserMailer.signup_confirmation(self).deliver
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :mobile, :email, :password, :avatar, :remove_avatar)}

		devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :mobile, :password, :current_password, :avatar, :remove_avatar)}
	end

	def after_sign_in_path_for(resource)
		stored_location_for(resource) || dashboard_index_path
	end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/desktops_controller.rb
class DesktopsController < ApplicationController
  load_and_authorize_resource
  def index
    @desktops = Desktop.all
  end

  def new
    @desktop = Desktop.new
  end 

  def edit
    @desktop = Desktop.find(params[:id])
  end
  
  def show
    @desktop = Desktop.find(params[:id])
  end

  def create
    @desktop = Desktop.new(desktop_params)  
    if(@desktop.save)
      redirect_to @desktop
    else
      render 'new'
    end
  end


  def update
    @desktop = Desktop.find(params[:id])
    
    if @desktop.update(desktop_params)
      redirect_to @desktop
    else
      render 'edit'
    end
  end

  def destroy
    @desktop = Desktop.find(params[:id])
    @desktop.destroy
    
    redirect_to desktops_path
  end

  private
    def desktop_params
      params.require(:desktop).permit(:emp_id, :asset_num,:name,:MAC_address,:comment, {images: []})
    end
end

app/controllers/laptops_controller.rb
class LaptopsController < ApplicationController
  load_and_authorize_resource
  def index
    @laptops = Laptop.all
  end

  def new
    @laptop = Laptop.new
  end 

  def edit
    @laptop = Laptop.find(params[:id])
  end
  
  def show
    @laptop = Laptop.find(params[:id])
  end

  def create
    @laptop = Laptop.new(laptop_params)  
    if(@laptop.save)
      redirect_to @laptop
    else
      render 'new'
    end
  end


  def update
    @laptop = Laptop.find(params[:id])
    
    if @laptop.update(laptop_params)
      redirect_to @laptop
    else
      render 'edit'
    end
  end

  def destroy
    @laptop = Laptop.find(params[:id])
    @laptop.destroy
    redirect_to laptops_path
  end

  private
    def laptop_params
      params.require(:laptop).permit(:emp_id, :asset_num,:name,:MAC_address,:charger_num,:comment, {images: []})
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/desktops_helper.rb
module DesktopsHelper
end

app/helpers/laptops_helper.rb
module LaptopsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<html>
  <head></head>
  <body class='dashboard_body'>
    <div class='dashboard_shade'>
			<div class='dashboard_welcome_body p-5'>
			WELCOME TO <span class='text-warning'>QWINIX</span> ASSET BOARD
			<div>
    </div>
  </body>
</html>

app/views/desktops/edit.html.erb
<div class='container mt-5 bg-warning pb-4 shadow-lg'>
  <div class="alert alert-danger text-center mb-5"><strong> EDIT DESKTOP </strong></div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <%= form_for :desktop, url: desktop_path(@desktop), method: :patch do |form| %>
        <div class="row mb-3">
          <%= form.label :Employee_ID, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:emp_id, {:class => "form-control"}) %>
          </div>
        </div>
    
        <div class="row mb-3">
          <%= form.label :Asset_number, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:asset_num, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :Name, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:name, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :MAC_Address, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:MAC_address, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :images, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.file_field(:images, multiple:true, :class => "form-control") %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :Comment, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_area(:comment, {:class => "form-control mb-4"}) %>
            <%= form.submit(:Update, {:class => "btn btn-success"}) %>
          </div>
        </div>
      </div>
      <div class="col-3">
        <% if @desktop.errors.any? %>
          <% @desktop.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>

  <%= link_to ' Back', desktops_path, :class => 'fa fa-reply btn btn-sm btn-dark' %>
</div>

app/views/desktops/index.html.erb
<html>
  <head></head>
  <body class='desktop_body'>
    <div class='dashboard_shade'>
    <% if can? :create, @desktop %>
      <%= link_to 'New Desktop', new_desktop_path,  :class => "btn btn-outline-warning mt-4"%>
    <%end%>
      <hr/> 
      <div class='bg-warning shadow-lg'>
        <table class="table">
          <thead class="bg-info text-white">
            <tr>
              <th scope="col">Employee_ID</th>
              <th scope="col">Asset_number</th>
              <th scope="col">Name</th>
              <th scope="col">MAC_address</th>
              <th scope="col">Comment</th>
              <th scope="col"> Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @desktops.each do |desktop| %>
              <tr>
                <td><%= desktop.emp_id %></td>
                <td><%= desktop.asset_num %></td>
                <td><%= desktop.name %></td>
                <td><%= desktop.MAC_address %></td>
                <td><%= desktop.comment %></td>
                <td><%= link_to " View", desktop_path(desktop), :class => 'fa fa-eye btn btn-sm btn-info'%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/views/desktops/new.html.erb
<div class='container mt-5 bg-warning pb-4 shadow-lg'>
  <div class="alert alert-secondary text-center mb-5"><strong> NEW DESKTOP </strong></div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <%= form_for :desktop, url: desktops_path do |form| %>
        

        <div class="row mb-3">
          <%= form.label :Employee_ID, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:emp_id, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :Asset_number, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:asset_num, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :Name, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:name, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :MAC_Address, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:MAC_address, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :images, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.file_field(:images, multiple:true, :class => "form-control") %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :Comment, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_area(:comment, {:class => "form-control mb-4"}) %>
            <%= form.submit({:class => "btn btn-success"}) %>
          </div>
        </div>        
        
      <% end %>
    </div>
    <div class="col-3">
    <% if @desktop.errors.any? %>
          <% @desktop.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <% end %>
        <% end %>
    </div>
  </div>

  <%= link_to ' Back', desktops_path, :class => 'fa fa-reply btn btn-sm btn-dark' %>
</div>

app/views/desktops/show.html.erb
<div class='container mt-5'>
  <div class='row'>
    <div class="col-6 shadow p-3 mb-5 bg-white rounded text-secondary">
      <p class="list-group-item list-group-item-success">
        <strong>Employee ID:</strong>
        <%= @desktop.emp_id %>
      </p>
      
      <p class="list-group-item list-group-item-warning">
        <strong>Asset number:</strong>
        <%= @desktop.asset_num %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Name:</strong>
        <%= @desktop.name %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>MAC Address:</strong>
        <%= @desktop.MAC_address %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Comment:</strong>
        <%= @desktop.comment %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Images:</strong>
        <% @desktop.images.each do |image| %>
          <%= link_to(image_tag(image.thumb.url), image.url) %>
        <% end %>
      </p>

      <% if can? :edit, @desktop %>
        <%= link_to " Edit", edit_desktop_path(@desktop), :class => 'fa fa-edit btn btn-sm btn-dark'%>
      <%end%>
      <% if can? :delete, @desktop %>
        <%= link_to " Delete", desktop_path(@desktop), :class => 'fa fa-trash btn btn-sm btn-danger',
                                method: :delete,
                                data: { confirm: 'Are you sure?' }%>
      <%end%>
    </div>
    <div class='col-1'></div>
    <div class='col-5 shadow p-3  bg-light rounded'>
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%=image_tag(@desktop.images.last.url ,:class=>'d-block w-100')if @desktop.images? %>
          </div>
          <% @desktop.images.each do |image| %>
            <div class="carousel-item">
              <%=image_tag(image.url, :class=>'d-block w-100' )%>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
      </div>
    </div>
  </div>
  <%= link_to ' Back', desktops_path, :class => 'fa fa-reply btn btn-sm btn-dark mb-3'%>
</div>

app/views/laptops/edit.html.erb
<div class='container mt-5 bg-warning pb-4 shadow-lg'>
  <div class="alert alert-danger text-center mb-5"><strong> EDIT LAPTOP </strong></div>
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <%= form_for :laptop, url: laptop_path(@laptop), method: :patch do |form| %>
        <% if @laptop.errors.any? %>
          <% @laptop.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger"><%= msg %></div>
          <% end %>
        <% end %>
  
        <div class="row mb-3">
          <%= form.label :Employee_ID, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:emp_id, {:class => "form-control"}) %>
          </div>
        </div>
    
        <div class="row mb-3">
          <%= form.label :Asset_number, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:asset_num, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :Name, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:name, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
          <%= form.label :MAC_Address, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_field(:MAC_address, {:class => "form-control"}) %>
          </div>
        </div>

        <div class="row mb-3">
					<%= form.label :Charger_num, :class=>'col-sm-3 col-form-label text-right'%>
					<div class='col-sm-9'>
						<%= form.text_field(:charger_num, {:class => "form-control"}) %>
					</div>
        </div>

        <div class="row mb-3">
					<%= form.label :images, :class=>'col-sm-3 col-form-label text-right'%>
					<div class='col-sm-9'>
						<%= form.file_field(:images, multiple: true, :class => "form-control") %>
					</div>
        </div>

        <div class="row mb-3">
          <%= form.label :Comment, :class=>'col-sm-3 col-form-label text-right'%>
          <div class='col-sm-9'>
            <%= form.text_area(:comment, {:class => "form-control mb-4"}) %>
            <%= form.submit(:Update, {:class => "btn btn-success"}) %>
          </div>
        </div>
      </div>
      <div class="col-3"></div>
    </div>
  <% end %>

  <%= link_to ' Back', laptops_path, :class => 'fa fa-reply btn btn-sm btn-dark' %>
</div>

app/views/laptops/index.html.erb
<html>
  <head></head>
  <body class='laptop_body'>
    <div class='dashboard_shade'>
      <% if can? :create, @laptop %>
        <%= link_to 'New Laptop', new_laptop_path,  :class => "btn btn-outline-warning mt-4"%>
      <%end%>  
      <hr /> 
      <div class='bg-warning shadow-lg'>
        <table class="table">
          <thead class="bg-info text-white">
            <tr>
              <th scope="col">Employee_ID</th>
              <th scope="col">Asset_number</th>
              <th scope="col">Name</th>
							<th scope="col">MAC_address</th>
							<th scope="col">Charger_num</th>
              <th scope="col">Comment</th>
              <th scope="col"> Actions</th>
            </tr>
          </thead>
          <tbody>
            <% @laptops.each do |laptop| %>
              <tr>
                <td><%= laptop.emp_id %></td>
                <td><%= laptop.asset_num %></td>
                <td><%= laptop.name %></td>
								<td><%= laptop.MAC_address %></td>
								<td><%= laptop.charger_num %></td>
                <td><%= laptop.comment %></td>
                <td><%= link_to " View", laptop_path(laptop), :class => 'fa fa-eye btn btn-sm btn-info'%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </body>
</html>

app/views/laptops/new.html.erb
<div class='container mt-5 bg-warning pb-4 shadow-lg'>
<div class="alert alert-secondary text-center mb-5"><strong> NEW LAPTOP </strong></div>
<div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <%= form_for :laptop, url: laptops_path do |form| %>
      <div class="row mb-3">
        <%= form.label :Employee_ID, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.text_field(:emp_id, {:class => "form-control"}) %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :Asset_number, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.text_field(:asset_num, {:class => "form-control"}) %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :Name, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.text_field(:name, {:class => "form-control"}) %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :MAC_Address, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.text_field(:MAC_address, {:class => "form-control"}) %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :Charger_num, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.text_field(:charger_num, {:class => "form-control"}) %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :images, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.file_field(:images, multiple: true, :class => "form-control") %>
        </div>
      </div>

      <div class="row mb-3">
        <%= form.label :Comment, :class=>'col-sm-3 col-form-label text-right'%>
        <div class='col-sm-9'>
          <%= form.text_area(:comment, {:class => "form-control mb-4"}) %>
          <%= form.submit({:class => "btn btn-success"}) %>
        </div>
      </div>        
    <% end %>
  </div>
  <div class="col-3">
    <% if @laptop.errors.any? %>
			<% @laptop.errors.full_messages.each do |msg| %>
				<div class="alert alert-danger"><%= msg %></div>
			<% end %>
    <% end %>
  </div>
</div>

<%= link_to ' Back', laptops_path, :class => 'fa fa-reply btn btn-sm btn-dark' %>
</div>

app/views/laptops/show.html.erb
<div class='container mt-5 '>
  <div class='row'>
    <div class="col-6 shadow p-3 mb-5 rounded text-secondary">
      <p class="list-group-item list-group-item-success">
        <strong>Employee ID:</strong>
        <%= @laptop.emp_id %>
      </p>
      
      <p class="list-group-item list-group-item-warning">
        <strong>Asset number:</strong>
        <%= @laptop.asset_num %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Name:</strong>
        <%= @laptop.name %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>MAC Address:</strong>
        <%= @laptop.MAC_address %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Charger Number:</strong>
        <%= @laptop.charger_num %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Comment:</strong>
        <%= @laptop.comment %>
      </p>

      <p class="list-group-item list-group-item-warning">
        <strong>Images:</strong>
        <% @laptop.images.each do |image| %>
          <%= link_to(image_tag(image.thumb.url), image.url) %>
        <% end %>
      </p>

      <% if can? :edit, @laptop %>
        <%= link_to " Edit", edit_laptop_path(@laptop), :class => 'fa fa-edit btn btn-sm btn-dark'%>
      <%end%>
      <% if can? :delete, @laptop %>
        <%= link_to " Delete", laptop_path(@laptop), :class => 'fa fa-trash btn btn-sm btn-danger',
                                method: :delete,
                                data: { confirm: 'Are you sure?' }%>
      <% end %>
    </div>
    <div class='col-1'></div>
    <div class='col-5 shadow p-3  bg-light rounded'>
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%=image_tag(@laptop.images.last.url ,:class=>'d-block w-100')if @laptop.images? %>
          </div>
          <% @laptop.images.each do |image| %>
            <div class="carousel-item">
              <%=image_tag(image.url, :class=>'d-block w-100' )%>
            </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </a>
      </div>
    </div>
  </div>
  <%= link_to ' Back', laptops_path, :class => 'fa fa-reply btn btn-sm btn-dark mb-3'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asset</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'%>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-dark bg-dark">
      <%= link_to image_tag("logo.png",:width=>'100', :height=>'30' ), dashboard_index_path %>
      <% if user_signed_in? %>        
        <form class="form-inline">
          <% if current_user.avatar? %> 
            <%= image_tag(current_user.avatar_url,:width=>'30', :height=>'30',:class=>'rounded-circle' )%>
          <% else %>
            <%= image_tag('default_avatar.jpeg',:width=>'40', :height=>'30',:class=>'rounded-circle' )%>
          <% end %> 
  
          <span class='text-light mr-3'>
            <strong class='text-warning ml-1'> <%= current_user.username %></strong>
            <% if current_user.admin? %> (admin) <% else %> (user) <% end %>
          </span>
          <%= link_to ' Desktops', desktops_path, :class => "fa fa-desktop btn btn-outline-warning mr-3"%> 
          <%= link_to ' Laptops', laptops_path, :class => "fa fa-laptop btn btn-outline-warning mr-3"%> 
          <%= link_to ' Miscellaneous', edit_user_registration_path, :class => "fa fa-microchip btn btn-outline-warning mr-3"%> 

          <%= link_to ' Edit profile', edit_user_registration_path, :class => "fa fa-pencil btn btn-outline-warning mr-3"%> 
          <%= link_to "Logout", destroy_user_session_path, method: :delete , :class => "btn btn-outline-info"%>
        </form>
      <% else %>
        <form class="form-inline">
          <%= link_to "Register", new_user_registration_path , :class => 'btn btn-light mr-3 btn-sm'%> |
          <%= link_to "Login", new_user_session_path, :class => 'btn btn-info mr-3 btn-sm' %>        
        </form>
      <% end %> 
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<html>
  <head></head>
  <body class='index_body'>
		<div class='shade'>
      <div class="content row">
        <div class='col-8 '>
          <h1 class='heading'>COMPANY ASSETS</h1>
          <p class='description'>It is the policy of Company that directors, officers, and employees are expected 
            to protect the assets of the Company and use them efficiently to advance the interests of 
            the Company. Those assets include tangible assets and intangible assets, such as confidential 
            information or the Company.</p>
        </div>
        <%= image_tag("computer.png",:class=>'computer' )%>
			</div>
    </div>
  </body>
</html>